[packages.pacman]
    to_remove = [
        "neofetch",
	"w3m",
    ]
[packages.pacman.base]
    packages = [
        "base-devel",
	"fastfetch",
	"fzf",
	"fd",
	"man-db",
	"man-pages",
	"neovim",
	"networkmanager",
	"ranger",
	"ripgrep",
	"starship",
	"trash-cli",
	"xdg-user-dirs",
	"xsel"
    ]
[packages.pacman.development_computer]
    packages = [
	"git",
	"github-cli",
	"jq",	
	"lazygit",
	"yq",
    ]
[packages.pacman.personal_computer]
    packages = [
	"elinks",
	"aerc",
	"keepassxc",
    ]
[packages.pacman.wm_computer]
    packages = []
[packages.yay]
    to_remove = []
[packages.yay.base]
    packages = [
        "fbterm",
    ]
[packages.yay.personal_computer]
    packages = []
[packages.yay.wm_computer]
    packages = []
[packages.apt]
    to_remove = [
        "neofetch",
	"w3m",
	"gnome-tour"
    ]
[packages.apt.base]
    packages = [
        "build-essential",
	"fastfetch",
	"fzf",
	"fd-find",
	"man-db",
	"manpages",
	"neovim",
	"network-manager",
	"ranger",
	"ripgrep",
	"starship",
	"trash-cli",
	"xdg-user-dirs",
	"xsel",
	"fbterm"
    ]
[packages.apt.dev_computer]
    packages = [
	"git",
	"jq",	
	"lazygit",
	"yq",
	"android-tools-adb",
	"fastboot"

    ]
[packages.apt.personal_computer]
    packages = [
	"elinks",
	"keepassxc",
    ]
[packages.apt.wm_computer]
    packages = []
[packages.flatpak]
    to_remove = []
[packages.flatpak.base]
    packages = []
[packages.flatpak.dev_computer]
    packages = []
[packages.flatpak.personal_computer]
    packages = []
[packages.flatpak.wm_computer]
    packages = []    
