[packages.flatpak]
    to_remove = [
    ]
[packages.flatpak.base]
    packages = [
    	"io.github.kolunmi.Bazaar",
    ]
[packages.flatpak.dev_computer]
    packages = [
    ]
[packages.flatpak.personal_computer]
    packages = [   
        "md.obsidian.Obsidian"
    ]
