[packages.pacman]
    to_remove = [
        "neofetch",
	"w3m",
    ]
[packages.pacman.base]
    packages = [
        "base-devel",
	"fastfetch",
	"fzf",
	"fd",
	"man-db",
	"man-pages",
	"neovim",
	"networkmanager",
	"ranger",
	"ripgrep",
	"starship",
	"trash-cli",
	"xdg-user-dirs",
	"xsel"
    ]
[packages.pacman.development_computer]
    packages = [
	"git",
	"github-cli",
	"jq",	
	"lazygit",
	"yq",
    ]
[packages.pacman.personal_computer]
    packages = [
	"elinks",
	"aerc",
	"keepassxc",
    ]

